CREATE VIEW view_projetos_status as
SELECT 
P.NOME_PROJETO,
S.NOME_STATUS,
P.DATA_CRIACAO_PROJETO,
P.DATA_PREVISAO_PROJETO 
FROM 
TB_PROJETOS P 
INNER JOIN   TB_STATUS_PROJETOS S ON 
P.STATUS_PROJETO = S.ID_STATUS;