CREATE TABLE TB_STATUS_FUNCIONARIOS(
	ID_STATUS SERIAL PRIMARY KEY,
	NOME_STATUS VARCHAR(25) UNIQUE NOT NULL
);

INSERT INTO TB_STATUS(NOME_STATUS) VALUES ('Ativo'),('Inativo'),('Afastado'),('Férias') ;
