CREATE TABLE TB_FUNCIONARIOS (
	ID_FUNCIONARIO SERIAL PRIMARY KEY,
	NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
	EMAIL_FUNCIONARIO VARCHAR(75) UNIQUE NOT NULL,
	CARGO_ID INT NOT NULL,
	STATUS_ID INT NOT NULL,
	SALARIO_FUNCIONARIO DECIMAL(15, 2),
	DATA_CRIACAO_FUNCIONARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MODIFICACAO_FUNCIONARIO TIMESTAMP,

	CONSTRAINT FK_FUNCIONARIO_STATUS FOREIGN KEY (STATUS_ID) REFERENCES TB_STATUS_FUNCIONARIOS (ID_STATUS),
	CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES TB_CARGO (ID_CARGO)
)