CREATE TABLE TB_INTER_CLI_PRO (
	FK_ID_CLIENTE INT NOT NULL ,
	FK_ID_PROJETO INT NOT NULL ,
	
	PRIMARY KEY (FK_ID_CLIENTE,FK_ID_PROJETO),
	
	CONSTRAINT FK_INTER_ID_CLIENTE
		FOREIGN KEY (FK_ID_CLIENTE) 
		REFERENCES TB_CLIENTES(ID_CLIENTE),
	
	CONSTRAINT FK_INTER_ID_PROJETO
		FOREIGN KEY (FK_ID_PROJETO)
		REFERENCES TB_PROJETOS(ID_CLIENTE)
);