CREATE TABLE TB_FUNCIONARIOS (
	ID_FUNCIONARIO SERIAL PRIMARY KEY,
	NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
	EMAIL_FUNCIONARIO VARCHAR(75) UNIQUE NOT NULL,
	CARGO_ID INT NOT NULL,
	CATEGORIA_ID INT NOT NULL,
	STATUS_ID INT NOT NULL,
	SALARIO_FUNCIONARIO DECIMAL(15, 2) NOT NULL, 
	DATA_CRIACAO_FUNCIONARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MODIFICACAO_FUNCIONARIO TIMESTAMP,

	CONSTRAINT FK_FUNCIONARIO_STATUS FOREIGN KEY (STATUS_ID) REFERENCES TB_STATUS_FUNCIONARIOS (ID_STATUS),
	CONSTRAINT FK_FUNCIONARIO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID_CATEGORIA),
	CONSTRAINT FK_FUNCIONARIO_CARGO FOREIGN KEY (CARGO_ID) REFERENCES TB_CARGOS (ID_CARGO)
)

INSERT INTO TB_FUNCIONARIOS(NOME_FUNCIONARIO,EMAIL_FUNCIONARIO,CARGO_ID,CATEGORIA_ID,STATUS_ID,SALARIO_FUNCIONARIO) VALUES
('Ana Oliveira','ana@tech.com',1, 1,1, 14800),
('Pedro Costa', 'pedro@tech.com',2,1,1, 12000),
('Carla Mendes', 'carla@tech.com',3,1,1, 9000),
('Mariana Silva', 'mariana@tech.com',4,1,1, 16500),
('Carlos Souza', 'carlos@tech.com',6,1,1, 6000),
('Fernando Lima', 'fernando@tech.com',5,1,1, 18000)

SELECT * FROM VW_FUNCIONARIOS

-- ======================{Views}============================
CREATE OR REPLACE VIEW VW_funcionarios as
	SELECT 
		F.NOME_FUNCIONARIO AS "Funcionário",
		F.EMAIL_FUNCIONARIO AS "Email",
		C.NOME_CARGO AS "Cargo",
		T.NOME_CATEGORIA AS "Senhoridade",
		S.NOME_STATUS AS "Status",
		F.SALARIO_FUNCIONARIO AS "Remuneração"
	FROM TB_FUNCIONARIOS F
	INNER JOIN TB_CARGOS C ON F.CARGO_ID = C.ID_CARGO   
	INNER JOIN TB_CATEGORIA T ON F.CATEGORIA_ID = T.ID_CATEGORIA
	INNER JOIN TB_STATUS_FUNCIONARIOS S ON F.STATUS_ID = S.ID_STATUS;