-- =====================================================
-- ================{TABELA_CLIENTES}====================
-- =====================================================
-- CLI = TB_CLIENTES
-- SEG = TB_SEGMENTOS
CREATE TABLE TB_INTER_CLI_SEG (
	ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	FK_ID_CLIENTE INT NOT NULL,
	FK_ID_SEGMENTO INT NOT NULL,

	CONSTRAINT FK_CLIENTE 
		FOREIGN KEY (FK_ID_CLIENTE)
		REFERENCES TB_CLIENTES(ID),
	
	CONSTRAINT FK_SEGMENTO 
		FOREIGN KEY (FK_ID_SEGMENTO) 
		REFERENCES TB_SEGMENTOS(ID_SEGMENTO)
)
-- /////////////////////////////////////////////////////

SELECT * FROM TB_SEGMENTOS

SELECT * FROM TB_CLIENTES

CREATE VIEW VW_INTER_NAME AS

	SELECT I.ID,C.NOME, S.NOME_SEGMENTO FROM TB_INTER_CLI_SEG I 
	INNER JOIN TB_SEGMENTOS S ON C.ID = S.ID_SEGMENTO ;
	INNER JOIN TB_CLIENTES C ON ;