-- =====================================================
-- ================{TABELA_CLIENTES}====================
-- =====================================================
-- CLI = TB_CLIENTES
-- SEG = TB_SEGMENTOS
CREATE TABLE TB_INTER_CLI_SEG (
	FK_ID_CLIENTE INT NOT NULL,
	FK_ID_SEGMENTO INT NOT NULL,

	CONSTRAINT FK_CLIENTE 
		FOREIGN KEY (FK_ID_CLIENTE)
		REFERENCES TB_CLIENTES(ID),
	
	CONSTRAINT FK_SEGMENTO 
		FOREIGN KEY (FK_ID_SEGMENTO) 
		REFERENCES TB_SEGMENTOS(ID_SEGMENTO),

	PRIMARY KEY (FK_ID_CLIENTE, FK_ID_SEGMENTO)		
);
-- /////////////////////////////////////////////////////

SELECT * FROM TB_SEGMENTOS

SELECT * FROM TB_CLIENTES

SELECT * FROM TB_INTER_cli_seg
CALL PR_CRIAR_CLIENTE('Empresa Beta','98.765.432/0001-10');

insert into TB_INTER_cli_seg(FK_ID_CLIENTE,FK_ID_SEGMENTO) values (1,2)

SELECT C.NOME_CLIENTE AS NOME_CLIENTE, S.NOME_SEGMENTO AS TB_SEGMENTOS FROM TB_INTER_CLI_SEG I 
INNER JOIN TB_CLIENTES C ON I.FK_ID_CLIENTE = C.ID_CLIENTE
INNER JOIN TB_SEGMENTOS S ON  I.FK_ID_SEGMENTO = S.ID_SEGMENTO;