CREATE TABLE TB_TAREFAS (
	ID_TAREFAS SERIAL PRIMARY KEY,
	ID_PROJETOS INT NOT NULL,
	NOME_TAREFAS VARCHAR(100) NOT NULL,
	DESCRICAO_TAREFAS TEXT NOT NULL,
	REQUERENTE_ID INT NOT NULL, 
	FUNCIONARIO_ID INT NOT NULL,
	PRIORIDADE_ID INT DEFAULT 2, --'2 = MÉDIA'
	DATA_CRIACAO_TAREFAS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MODIFICACAO_TAREFAS TIMESTAMP,
	DATA_FINALIZACAO TIMESTAMP,

	CONSTRAINT FK_ID_PROJETOS FOREIGN KEY (ID_PROJETOS) REFERENCES TB_PROJETOS(ID_PROJETOS),
	CONSTRAINT FK_ID_REQUERENTE FOREIGN KEY (REQUERENTE_ID) REFERENCES TB_FUNCIONARIOS(ID_FUNCIONARIO),
	CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID) REFERENCES TB_FUNCIONARIOS(ID_FUNCIONARIO),
	CONSTRAINT FK_ID_PRIORIDADE FOREIGN KEY (PRIORIDADE_ID) REFERENCES TB_PRIORIDADE_TAREFAS(ID_PRIORIDADE)
);
 