-- =====================================================
-- ================{TABELA_CLIENTES}====================
-- =====================================================
-- CLI = TB_CLIENTES
-- SEG = TB_SEGMENTOS
CREATE TABLE TB_INTER_CLI_SEG (
	FK_ID_CLIENTE INT NOT NULL,
	FK_ID_SEGMENTO INT NOT NULL,

	CONSTRAINT FK_CLIENTE 
		FOREIGN KEY (FK_ID_CLIENTE)
		REFERENCES TB_CLIENTES(ID),
	
	CONSTRAINT FK_SEGMENTO 
		FOREIGN KEY (FK_ID_SEGMENTO) 
		REFERENCES TB_SEGMENTOS(ID_SEGMENTO),

	PRIMARY KEY (FK_ID_CLIENTE, FK_ID_SEGMENTO)		
);
-- /////////////////////////////////////////////////////

SELECT * FROM TB_SEGMENTOS

SELECT * FROM TB_CLIENTES

SELECT * FROM TB_INTER_cli_seg

CALL PR_CRIAR_CLIENTE('Empresa Beta','98.765.432/0001-10');
CALL PR_CRIAR_CLIENTE('Empresa Gama','45.678.901/0001-20');
CALL PR_CRIAR_CLIENTE('Empresa Delta','67.890.123/0001-30');


