CREATE TABLE TB_PROJETOS(
	ID_PROJETO SERIAL PRIMARY KEY,
	CLIENTE_ID INT ,
	RESPONSAVEL_ID INT,
	
	NOME_PROJETO VARCHAR(100) NOT NULL,
	STATUS_PROJETO int DEFAULT 1,
	
	DATA_CRIACAO_PROJETO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DATA_MODIFICACAO_PROJETO TIMESTAMP,
	DATA_ENTREGA_PROJETO TIMESTAMP,
	VALOR_ESTIMADO DECIMAL(15,2)
	
	CONSTRAINT FK_STATUS_PROJETO FOREIGN KEY (STATUS_PROJETO) REFERENCES TB_STATUS_PROJETOS(ID_STATUS),
	CONSTRAINT FK_PROJETO_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES TB_CLIENTES(ID_CLIENTE),
	CONSTRAINT FK_RESPONSAVEL_PROJETO FOREIGN KEY (RESPOSAVEL_ID)REFERENCES TB_FUNCIONARIO(ID_FUNCIONARIO)
);