CREATE SEQUENCE ID_FUNCIONARIO_SEQUENCE;

CREATE TABLE TB_FUNCIONARIOS
(
	ID_FUNCIONARIO VARCHAR(10) PRIMARY KEY DEFAULT ('F' || LAPAD(NEXTVAL('ID_FUNCIONARIO_SEQUENCE')::TEXT 3,'0')),
	NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
	EMAIL_FUNCIONARIO VARCHAR(50) NOT NULL UNIQUE,
	DEPARTAMENTO REFERENCES TB_DEPARTAMENTO(ID_DEPARTAMENTO),
	
	CARGO_FUNCIONARIO INT REFERENCES TB_CARGO(ID_CARGO),
	
)

SELECT * FROM VIEW_CLIENTES_SEGMENTOS;