CREATE TABLE TB_CATEGORIA (
	ID_CATEGORIA SERIAL PRIMARY KEY,
	 NOME_CATEGORIA VARCHAR(50) NOT NULL,
	 SIGLA_CATEGORIA CHAR(9) NOT NULL
);

CREATE UNIQUE INDEX idx_nome_categoria ON
TB_CATEGORIA(LOWER(TRIM(NOME_CATEGORIA)));

INSERT INTO TB_CATEGORIA (NOME_CATEGORIA, SIGLA_CATEGORIA) VALUES 
('Sênior','SN'),
('Pleno', 'PL'),
('Júnior', 'JR'),
('Estagiário', 'ETG')

SELECT * FROM tb_categoria;