CREATE TABLE TB_CARGOS (
	ID_CARGO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DEPARTAMENTO_ID INT NOT NULL,
	NOME_CARGO VARCHAR(100) NOT NULL,
	SALARIO_BASE DECIMAL(15,2)
);

INSERT INTO TB_CARGOS (NOME_CARGO) VALUES
('Arquiteto Soluções'),
('Dev Sênior'),
('Designer UX'),
('Engenheiro Dados'),
('Engenheiro IoT'),
('Dev Frontend');

SELECT *FROM TB_CARGOS;