CREATE TABLE TB_DEPARTAMENTO(
	ID_DEPARTAMENTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NOME_DEPARTAMENTO VARCHAR(50) NOT NULL UNIQUE,
	SIGLA_DEPARTAMENTO CHAR(3) NOT NULL UNIQUE
);

INSERT INTO TB_DEPARTAMENTO(NOME_DEPARTAMENTO,SIGLA_DEPARTAMENTO) VALUES
('Engenharia','ENG'),
('Design','DES'),
('Dados','DAD'),
('Hardware', 'HWD');